### ISSUE TITLE
Bug in iniParam

### ISSUE THREAD

**Issue by miguel-porto** [guiblanchet/HMSC#10]
Hello,
I think there's a bug in [this line](https://github.com/guiblanchet/HMSC/blob/2fe4e0e4c8ed8396c8487af40a6471e0333881ae/R/iniParamXTr.R#L71):
Instead of
`precX <- rWishart(1,paramX+1,diag(nparamX))[,,1]`
it should be, I guess:
`precX <- rWishart(1,nparamX+1,diag(nparamX))[,,1]`

(paramX is a matrix, not a number)
The same for [this line](https://github.com/guiblanchet/HMSC/blob/2fe4e0e4c8ed8396c8487af40a6471e0333881ae/R/iniParamX.R#L71) also.

I hope I'm seeing it right.
Best,
Miguel

**Comment by guiblanchet** [comment]
Thanks !

Again, I forgot to answer this comment following my correction. I also just realized that I had forgotten to make the correction in the iniParamXTr function. Now it is corrected
