### ISSUE TITLE
Fix bug in predict.hmsc

### ISSUE THREAD

**Issue by miguel-porto** [guiblanchet/HMSC#6]
Hi,
I think there's another minor fix needed in this line:
[https://github.com/guiblanchet/HMSC/blob/master/R/predict.hmsc.R#L166](https://github.com/guiblanchet/HMSC/blob/master/R/predict.hmsc.R#L166)

It should be
`niter<-dim(object$results$estimation$paramLatent)[1]`

because we may have multiple columns in this matrix, so the length may not be equal to the number of iterations.
Best,
Miguel

**Comment by guiblanchet** [comment]
Hi ! 

Thanks, I just realized that I had not answer this comment. 

In short, it has been corrected using `nrow`
